wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: train/photometric_error
      6:
      - 3
      7:
      - 1
    - 1: train/disparity_smoothness_loss
      6:
      - 3
      7:
      - 1
    - 1: train/geometry_consistency_loss
      6:
      - 3
      7:
      - 1
    - 1: train/total_loss
      6:
      - 3
      7:
      - 1
    - 1: val/photometric_error
      6:
      - 3
      7:
      - 1
    - 1: val/disparity_smoothness_loss
      6:
      - 3
      7:
      - 1
    - 1: val/geometry_consistency_loss
      6:
      - 3
      7:
      - 1
    - 1: val/total_loss
      6:
      - 3
      7:
      - 1
    - 1: learning_rate
      6:
      - 3
      7:
      - 5
    python_version: 3.6.9
    start_time: 1653245197
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      3:
      - 7
      - 13
      4: 3.6.9
      5: 0.12.16
      8:
      - 5
